# Generated by Django 2.1.3 on 2018-12-07 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans', to=settings.AUTH_USER_MODEL)),
                ('follow_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_friend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
