# Generated by Django 2.1.3 on 2018-12-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
